env:
  es2020: true
  node: true
  jest: true
extends:
  - airbnb-base
  - plugin:@typescript-eslint/recommended
  - prettier/@typescript-eslint
  - plugin:prettier/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - "@typescript-eslint"
  - prettier
rules:
  {
    "prettier/prettier": "error",
    "import/extensions": ["error", "ignorePackages", { "ts": "never" }],
    "import/prefer-default-export": off,
    "import/no-unresolved": 0,
    "class-methods-use-this": 0,
    "no-unused-vars": 0,
    "@typescript-eslint/no-unused-vars": ["off"],
  }
settings:
  import/resolver:
    typeScript:
